### ISSUE TITLE
Help with doors

### ISSUE THREAD

**Issue by TheNooseMan87** [pk-hack/CoilSnake#230]
So, I'm still very new to Coilsnake, and trying to learn about door, but It's not working for me. I try to make the door in Ness' room go to Onett. So, I put in the coordinates "44, 33". and it takes me to 11, 8, whenever I click, "Jump to location".  And whenever I play my rom, the door is gone. i just go right through it. I have no idea what I'm doing wrong and any help would be appreciated.

**Comment by Messianic** [comment]
Some things you need to do: Make sure that you set the Type as "Door", and its a good idea to have "1" as the Warp Style. Make sure you hit APPLY CHANGES< and also make sure you save the rom in the EBPRojectEditor.

Also the spot you place a door on MUST be on a spot that has a "90" for its minitile. Go into the Tile Editor and take a peek at doors and notice in the 4x4 grid of double digits by the bottom right, that the exact minitile has a "90" for its setting. As long as your door is place a spot with that it will work, otherwise it will not.

**Comment by TheNooseMan87** [comment]
So, just tried it and the door worked! but now im in Tenda village. Is it possible that the coordinates that displays at the top of the map editor are different from the ones shown in the door editor?

**Comment by Messianic** [comment]
You want to be looking at the BOTTOM of your screen, particularly at the "WARP X, Y" coordinates. Those are set to the minitiles. If you are not seeing it go to "Options > Show Coordinates"

**Comment by TheNooseMan87** [comment]
Thanks, it worked!

**Comment by ShadowOne333** [comment]
Problem solved by Messianic. Closing issue.
