### ISSUE TITLE
naming_skip.yml doesn't work with control codes

### ISSUE THREAD

**Issue by RudieRadioWaves** [pk-hack/CoilSnake#239]
After creating custom font characters and verifying they work in the regular naming menu, trying to apply the naming_skip.yml patch using names that contain these new font characters results in a garbled string of characters. I then tried control codes of font characters that were already in vanilla Earthbound, but those gave the same results. 

I've attached a screenshot of the issue in action.

![unknown](https://user-images.githubusercontent.com/77852251/109058699-9b4b7700-76e3-11eb-95db-18de379b66c2.png)

**Comment by ShadowOne333** [comment]
Are you properly writing the hexadecimal codes to the YML?
For example:
`Name1: [90][A0][B0][C0]`
That should give Ness whichever characters you have at hex positions 90, A0, B0 and C0.

If simply putting them in square brackets doesn't work, try closing the whole hex values inside quotation marks.

**Comment by stochaztic** [comment]
@ShadowOne333 's suggestion above will not work as the [SkipNamingModule](https://github.com/pk-hack/CoilSnake/blob/master/coilsnake/modules/eb/SkipNamingModule.py) file is using a `ord(c) + 30` loop instead of the [standard_text_to_byte_list](https://github.com/pk-hack/CoilSnake/blob/685df8cad43a5a5b716f4106a03ee20b6bccae7e/coilsnake/util/eb/text.py#L16) method. I am not currently in a position to write a patch to fix the `SkipNamingModule.py` file to use that method instead of writing its own loop, but I suspect that would solve the issue.

**Comment by stochaztic** [comment]
Fixed in [v4.1](https://github.com/pk-hack/CoilSnake/releases/tag/4.1).
