### ISSUE TITLE
"Sprite Group #001 uses an invalid palette"

### ISSUE THREAD

**Issue by wolosolo** [pk-hack/CoilSnake#300]
![001](https://github.com/user-attachments/assets/214e662a-9014-4c99-b78c-4eb77233f3c9)

its literally small eyed hatless ness. wat

i don't get whats wrong, it just doesn't make any sense!
the only explanation there is, is that i DID borrow the magicant ness outline, y'know?, THE SAME OUTLINE COLLOR
USED BY EVERY SINGLE SPRITE IN THE GAME, so yeah, any answers? (sorry for bad english)

**Comment by Supremekirb** [comment]
I assume you mean "incorrect palette"... You will need to use a program that supports something called indexed colour. If you don't know what it means, look it up. I recommend GraphicsGale or LibreSprite. MSPaint, Paint.NET, and some others won't work because they don't support the format.

**Comment by PhoenixBound** [comment]
Sprite groups, for sprites on the overworld, can only use one of the palettes listed in sprite\_group\_palettes.yml. "Using one of those palettes" means that all the colors need to be the exact same, in exactly the same order, as one of the lists of 16 colors in that file. There are some workarounds that let you use different colors for sprites in a specific map (the game will do that if you use palette 4 in that file), but if you want a sprite that looks the same everywhere, then you need to use one of the other 7 palettes in sprite\_group\_palettes.yml.

In your sprite, you edited one of the darker shades of red to be a different light tan color. This caused the palette to not match any of the palettes in that file, which means CoilSnake no longer knows which palette to give that sprite.

**Comment by wolosolo** [comment]
is it RGB, HSL or HSV, also, in what order DO i put in?

![Captura de tela 2024-09-15 165605](https://github.com/user-attachments/assets/d8309951-ebb1-45e2-800f-b46e68fe48f3)

**Comment by PhoenixBound** [comment]
The numbers I gave were RGB values (and that's also the format in the mentioned YML file). They're listed in the order you're supposed to input them.

If you're unsure about what to do, open another party member's sprite, or another of Ness's sprites. They should have the correct palette, so you can compare them.

**Comment by wolosolo** [comment]
ok, so, i know, im a dumb b, but can you see whats wrong with this one please? Sorry for the dumbness im new to this stuff

![461](https://github.com/user-attachments/assets/e42d4aa8-85af-49a6-9ad2-750ce3c472f0)

**Comment by wolosolo** [comment]
![desapontamento](https://github.com/user-attachments/assets/e73f71c8-f19e-4f66-9f21-4c1963b98c7c)

**Comment by PhoenixBound** [comment]
Please don't repeatedly close and open an issue with no explanation. Especially if you delete the part where you were actually asking a question. All it does is spam the maintainers' emails, and make it look like you figured out the issue yourself when you closed the issue.

Below is what I wrote and was about to send right before you closed the issue the first time.

---

You ran into the same issue, and you fix it the same way.

![Before](https://github.com/user-attachments/assets/d027bd60-638c-4e24-95ee-6e0c79f52a2c)
![After](https://github.com/user-attachments/assets/8c42d309-c357-4224-8e87-234a970991f9)

Find a sprite in your CoilSnake project that's supposed to have the same palette as this one, and replace all of the colors in this sprite with the colors from the working sprite.

I don't know what you're doing that causes the palette to be darker/washed out compared to the original PNG, but uh... stop doing that. The colors should stay exactly the same as how CoilSnake dumps them if you want to use the original sprites' colors. **An easy way to ensure this is by opening one of the original sprites' PNGs in GraphicsGale and 📋 pasting your sprite into it**, rather than manually adjusting colors. (If you want to change the colors/add a brand new palette for your custom sprite, you can do that by following [the tutorial page I linked earlier in this thread](https://github.com/pk-hack/CoilSnake/wiki/Adding-a-New-Sprite-Palette).)

**Comment by wolosolo** [comment]
ok
